const GET_BIRTH_DATE = 'GET_BIRTH_DATE'
const DATA_STAFF_OF_MONTH = 'DATA_STAFF_OF_MONTH'
const GET_PENDING = 'GET_PENDING'
const GET_SENT = 'GET_SENT'
const INFO_USER = 'INFO_USER'
const DATA_READY_SENTSMS = 'DATA_READY_SENTSMS'
const REMOVE_ITEM_DATA_SENTSMS = 'REMOVE_ITEM_DATA_SENTSMS'
const AUTH_TOKEN = 'AUTH_TOKEN'
const ROLE_AUTH = 'ROLE_AUTH'
const STAFF_ID = 'STAFF_ID'
const DATA_LOADING = 'DATA_LOADING'
const MAP_DATA_SEND_SMS = 'MAP_DATA_SEND_SMS'
const IS_LOADING_SMS = 'IS_LOADING_SMS'
const IS_LOADING_SMS_PENDING = 'IS_LOADING_SMS_PENDING'
const STAFF_FORWARD = 'STAFF_FORWARD'
const STAFF_FORWARD_SMS = 'STAFF_FORWARD_SMS'
const PAGE_STAGE = 'PAGE_STAGE'
export {
  MAP_DATA_SEND_SMS,
  STAFF_FORWARD_SMS,
  IS_LOADING_SMS,
  STAFF_FORWARD,
  GET_BIRTH_DATE,
  DATA_LOADING,
  DATA_STAFF_OF_MONTH,
  INFO_USER,
  GET_PENDING,
  GET_SENT,
  DATA_READY_SENTSMS,
  REMOVE_ITEM_DATA_SENTSMS,
  IS_LOADING_SMS_PENDING,
  AUTH_TOKEN,
  ROLE_AUTH,
  PAGE_STAGE,
  STAFF_ID
}
