const TOTAL_BIRTH_DATE = 'TOTAL_BIRTH_DATE'
const DATA_STAFF_OF_MONTH = 'DATA_STAFF_OF_MONTH'
const DATA_RECENT_SMS = 'DATA_RECENT_SMS'
const DATA_PERSONALISED_STATS = 'DATA_PERSONALISED_STATS'
const DATA_MANAGER = 'DATA_MANAGER'
const INFO_USER = 'INFO_USER'
const DATA_DEPARTMENT = 'DATA_DEPARTMENT'
const ACCESS_TOKEN = 'ACCESS_TOKEN'
const LOGOUT_AUTH = 'LOGOUT_AUTH'
const ROLE_AUTH = 'ROLE_AUTH'
const PREFERRED_NAME = 'PREFERRED_NAME'
const GET_STAFF_BY_SEARCH = 'GET_STAFF_BY_SEARCH'
const DATA_ROLE_STAFF = 'DATA_ROLE_STAFF'
const UPDATE_ROLE_STAFF = 'UPDATE_ROLE_STAFF'
const STAFF_AUTH = 'STAFF_AUTH'
const SENT_SMS = 'SENT_SMS'
const CREATE_FUNCTION_ID = 'CREATE_FUNCTION_ID'
const SEARCH_FUNCTION_ID = 'SEARCH_FUNCTION_ID'
const DEACTIVE_FUNCTION_ID = 'DEACTIVE_FUNCTION_ID'
const GET_OUTLET_CODE = 'GET_OUTLET_CODE'
const DATA_TEMPLATES = 'DATA_TEMPLATES'
const CREATE_OR_UPDATE_TEMPLATE = 'CREATE_OR_UPDATE_TEMPLATE'
const PAGE_ACTIVE = 'PAGE_ACTIVE'
const DATA_LOADING = 'DATA_LOADING'
const DATA_SEND_SMS = 'DATA_SEND_SMS'

export {
  TOTAL_BIRTH_DATE,
  DATA_STAFF_OF_MONTH,
  DATA_RECENT_SMS,
  DATA_PERSONALISED_STATS,
  DATA_DEPARTMENT,
  DATA_MANAGER,
  INFO_USER,
  ACCESS_TOKEN,
  LOGOUT_AUTH,
  ROLE_AUTH,
  GET_STAFF_BY_SEARCH,
  DATA_ROLE_STAFF,
  UPDATE_ROLE_STAFF,
  STAFF_AUTH,
  SENT_SMS,
  CREATE_FUNCTION_ID,
  SEARCH_FUNCTION_ID,
  DEACTIVE_FUNCTION_ID,
  GET_OUTLET_CODE,
  DATA_TEMPLATES,
  DATA_LOADING,
  PREFERRED_NAME,
  CREATE_OR_UPDATE_TEMPLATE,
  PAGE_ACTIVE,
  DATA_SEND_SMS
}
