const GET_DATA_TRANSACTION = 'GET_DATA_TRANSACTION'
const GET_STAFF_PORTAL = 'GET_STAFF_PORTAL'
const GET_VOUCHER_STAFF = 'GET_VOUCHER_STAFF'
const POST_VOUCHER_REDEMPTION = 'POST_VOUCHER_REDEMPTION'
const EXPORT_EXCEL = 'EXPORT_EXCEL'
const EXPORT_PDF = 'EXPORT_PDF'
const DATA_LOADING = 'DATA_LOADING'
export {
  GET_DATA_TRANSACTION,
  GET_STAFF_PORTAL,
  GET_VOUCHER_STAFF,
  POST_VOUCHER_REDEMPTION,
  EXPORT_EXCEL,
  DATA_LOADING,
  EXPORT_PDF
}
